# Generated by Django 5.0.6 on 2024-06-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactdetails_delete_contactus_remove_contact_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetails',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='phone',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
