# Generated by Django 5.0.6 on 2024-06-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_contactdetails_siteconfiguration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='about',
            field=models.ImageField(null=True, upload_to='abouts/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero',
            field=models.ImageField(null=True, upload_to='heros/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
