# Generated by Django 5.0.6 on 2024-06-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siteconfiguration_about_siteconfiguration_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about',
            field=models.ImageField(default='', upload_to='abouts/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero',
            field=models.ImageField(default='', upload_to='heros/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_subtitle',
            field=models.CharField(default='Discover our amazing services', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(default='Welcome to My Website', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(default='', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='My Website', max_length=100),
        ),
    ]
