# Generated by Django 5.0.6 on 2024-06-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
